version: '3.8'
services:
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: projects
    stdin_open: true
    tty: true
    volumes:
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/1.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASSWORD: "1234"
      DB_NAME: projects